# Generated by Django 4.2.7 on 2023-12-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_post_priority_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('I', 'In Progress'), ('D', 'Done')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
